baseurl: "/"
languageCode: "fr-fr"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Accueil
      url: ""
      weight: 1
    - name: Questions
      url: "categories/"
      weight: 2
    - name: Sujets
      url: "tags/"
      weight: 3

params:
  description: "Sylviculture en question"
  footer: "&copy; [LaBuse](https://labuse.net) 2021"

markup:
  goldmark:
    renderer:
      unsafe: true

